# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171227_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='something',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
