# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 05:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userinfo_something'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
    ]
