# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171228_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='topicname',
            new_name='topic',
        ),
    ]
