# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_answer_ansimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ansimage',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
