# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180102_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userimg',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
