# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180102_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('created',)},
        ),
    ]
