# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180103_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ansagainst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='ansagree',
            field=models.IntegerField(default=0),
        ),
    ]
