# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180104_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isread',
            field=models.IntegerField(default=0),
        ),
    ]
